name: build-deploy

on: push

jobs:
  build:
    if: github.event.head_commit.message == 'deploy'
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        run: ls -la .
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.FRONT_DEPLOY_PATH }}
  
  deploy:
    needs: build
    if: github.event.head_commit.message == 'deploy'
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        run: ls -la .
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.FRONT_DEPLOY_PATH }}
